name: CI (Libretro - iOS)

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      - name: Build
        run: |
          make -f Makefile.libretro \
            platform=ios-arm64 \
            VERBOSE=1 \
            -j$(nproc)

      - name: Locate and Rename Artifact
        run: |
          mkdir -p output/
          find . -name "*.dylib" -exec cp {} output/ \;
          ls -la output/
            
      - name: Upload Built Binaries
        uses: actions/upload-artifact@v4
        with:
         name: theseuscdi-libretro-ios
         path: output/
